# Generated by Django 3.1.1 on 2020-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registro', models.CharField(max_length=20)),
                ('IdUsuario', models.IntegerField(default=0)),
                ('MovimientoAct', models.CharField(max_length=20)),
                ('MovimientoTabla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idempleado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField(default=0)),
                ('Correo', models.EmailField(max_length=20)),
                ('ApellidoM', models.CharField(max_length=15)),
                ('ApellidoP', models.CharField(max_length=15)),
                ('Sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(default=0)),
                ('TipoPago', models.CharField(max_length=20)),
                ('IdCliente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMateriaPrima', models.IntegerField(default=0)),
                ('IdMateriaCompra', models.IntegerField(default=0)),
                ('Cantidad', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=0)),
                ('Descripcion', models.TextField(max_length=100)),
                ('IdProducto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('ApellidoP', models.CharField(max_length=20)),
                ('ApellidoM', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=40)),
                ('Rfc', models.CharField(max_length=25)),
                ('Telefono', models.IntegerField(default=0)),
                ('Sexo', models.CharField(max_length=10)),
                ('Cargo', models.CharField(max_length=20)),
                ('Salario', models.IntegerField(default=0)),
                ('EstadoCivil', models.CharField(max_length=15)),
                ('Nss', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20)),
                ('Pregunta1', models.CharField(max_length=70)),
                ('Pregunta2', models.CharField(max_length=70)),
                ('Pregunta3', models.CharField(max_length=70)),
                ('Pregunta4', models.CharField(max_length=70)),
                ('Pregunta5', models.CharField(max_length=70)),
                ('Pregunta6', models.CharField(max_length=70)),
                ('Pregunta7', models.CharField(max_length=70)),
                ('Pregunta8', models.CharField(max_length=70)),
                ('Pregunta9', models.CharField(max_length=70)),
                ('Pregunta10', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorasTrabajadas', models.IntegerField(default=0)),
                ('DiasTrabajados', models.IntegerField(default=0)),
                ('PagoHora', models.FloatField(default=0)),
                ('HorasExtra', models.FloatField(default=0)),
                ('Bonos', models.FloatField(default=0)),
                ('IdEmpleado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=20)),
                ('IdMob', models.IntegerField(default=0)),
                ('CostoMan', models.FloatField(default=0)),
                ('IdEmpleado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=70)),
                ('Precio', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Existencias', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Nic', models.IntegerField(default=0)),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEmpleado', models.IntegerField(default=0)),
                ('Sal', models.IntegerField(default=0)),
                ('MetodoPago', models.CharField(max_length=30)),
                ('Des', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCliente', models.IntegerField(default=0)),
                ('Precio', models.FloatField(default=0)),
                ('Cantidad', models.FloatField(default=0)),
                ('Direccion', models.CharField(max_length=50)),
                ('IdProducto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField(default=0)),
                ('ActPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ActConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('AsisPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('AsisConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('BalPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('BalConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('CliPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('CliConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ComPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ComConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('DcomPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('DcomConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('DevPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('DevConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('EmpPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('EmpConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('EvaPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('EvaConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('JorPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('JorConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ManPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ManConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('MatPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('MatConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('MobPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('MobConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('PagoPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('PagoConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('PedidoPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('PedidoConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProduPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProduConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProvePermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProveConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProyePermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('ProyeConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('RemPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('RemConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('UsuarioPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('UsuarioConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('VentaPermiso', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
                ('VentaConsulta', models.BooleanField(default=False, verbose_name='Activada/No Activada')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('PrecioV', models.FloatField(default=0)),
                ('PrecioC', models.FloatField(default=0)),
                ('Cantidad', models.FloatField(default=0)),
                ('CantMin', models.FloatField(default=0)),
                ('CantMax', models.FloatField(default=0)),
                ('Categoria', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField(default=0)),
                ('Direccion', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=30)),
                ('Rfc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePro', models.CharField(max_length=20)),
                ('TipoPro', models.CharField(max_length=20)),
                ('IdEmpleado', models.IntegerField(default=0)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Remplazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMobiliario', models.IntegerField(default=0)),
                ('Costo', models.FloatField(default=0)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Tipo', models.IntegerField(default=0)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCliente', models.IntegerField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('TipoPago', models.IntegerField(default=0)),
            ],
        ),
    ]
