# Generated by Django 3.1.1 on 2020-10-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['Registro'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['Nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
