# Generated by Django 3.1.1 on 2020-10-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0002_auto_20201025_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Tipo',
        ),
    ]
