# Generated by Django 3.1.1 on 2020-10-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0004_usuario_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['Nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
