# Generated by Django 3.1.1 on 2020-10-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0006_auto_20201026_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permisos',
            new_name='Permiso',
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['Nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['NombrePro'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='remplazo',
            options={'ordering': ['IdMobiliario'], 'verbose_name': 'Remplazo', 'verbose_name_plural': 'Remplazos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['Fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
