# Generated by Django 3.1.1 on 2020-10-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0007_auto_20201028_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiliario',
            options={'ordering': ['Nombre'], 'verbose_name': 'Mobiliario', 'verbose_name_plural': 'Mobiliarios'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['IdEmpleado'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['Fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['Nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['Nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='remplazo',
            options={'ordering': ['Descripcion'], 'verbose_name': 'Remplazo', 'verbose_name_plural': 'Remplazos'},
        ),
        migrations.RenameField(
            model_name='materiaprima',
            old_name='Existencias',
            new_name='Existencia',
        ),
    ]
