# Generated by Django 3.1.1 on 2020-10-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas', '0009_auto_20201028_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['IdEmpleado'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['FechaInicio'], 'verbose_name': 'Balance', 'verbose_name_plural': 'Balances'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['Fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'ordering': ['IdMateriaPrima'], 'verbose_name': 'DetalleCompra', 'verbose_name_plural': 'DetalleCompras'},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['IdUsuario'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='Idempleado',
            new_name='IdEmpleado',
        ),
    ]
