from django.contrib import admin
from. models import *
# Register your models here.
admin.site.register(Actividad)
admin.site.register(Asistencia)
admin.site.register(Balance)
admin.site.register(Cliente)
admin.site.register(Compra)
admin.site.register(DetalleCompra)
admin.site.register(Devolucion)
admin.site.register(Empleado)
admin.site.register(Evaluacion)
admin.site.register(Jornada)
admin.site.register(Mantenimiento)
admin.site.register(MateriaPrima)
admin.site.register(Mobiliario)
admin.site.register(Pago)
admin.site.register(Pedido)
admin.site.register(Permiso)
admin.site.register(Producto)
admin.site.register(Proveedor)
admin.site.register(Proyecto)
admin.site.register(Remplazo)
admin.site.register(Usuario)
admin.site.register(Venta)
